[constitutional_ai]
enable_constitutional_ai = true
enable_real_time_verification = true
enable_bias_detection = true
enable_harm_prevention = true

[thresholds]
verification_threshold = 0.85
safety_threshold = 0.9
bias_threshold = 0.5
harm_threshold = 0.3

[correction]
max_correction_attempts = 3
enable_self_correction = true
log_all_interventions = true

[principles]
helpfulness_weight = 1.0
harmlessness_weight = 1.5
honesty_weight = 1.2
respect_weight = 1.3

[integration]
use_middleware = true
verify_inputs = true
verify_outputs = true
enable_api = true